development:
  adapter: postgresql
  encoding: unicode
  database: gif_overflow_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: gif_overflow_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: gif_overflow_production
  pool: 5
